### ISSUE TITLE
On starting the server I got a new error with the template.

### ISSUE THREAD

**Issue by denny** [denny/ShinyCMS-ruby#300]
Now the process end successfully, but on starting the server I got a new related error with the template.

i will take a look over it and I let you know...

```
  ↳ app/models/page_section.rb:104:in `default_section'
  Page Load (0.3ms)  SELECT "pages".* FROM "pages" WHERE "pages"."section_id" IS NULL AND "pages"."hidden" = $1 ORDER BY "pages"."sort_order" ASC  [["hidden", false]]
  ↳ app/models/page.rb:97:in `min'
  CACHE Setting Load (0.0ms)  SELECT "settings".* FROM "settings" WHERE "settings"."name" = $1 LIMIT $2  [["name", "theme_name"], ["LIMIT", 1]]
  ↳ app/models/setting.rb:49:in `get'
  CACHE SettingValue Load (0.0ms)  SELECT "setting_values".* FROM "setting_values" WHERE "setting_values"."setting_id" = $1 LIMIT $2  [["setting_id", 10], ["LIMIT", 11]]
  ↳ app/models/setting.rb:22:in `setting_value'
  CACHE SettingValue Load (0.0ms)  SELECT "setting_values".* FROM "setting_values" WHERE "setting_values"."setting_id" = $1 AND "setting_values"."user_id" IS NULL LIMIT $2  [["setting_id", 10], ["LIMIT", 1]]
  ↳ app/models/setting.rb:23:in `setting_value'
Completed 500 Internal Server Error in 313ms (ActiveRecord: 42.9ms | Allocations: 248057)

 
NoMethodError (undefined method `page_templates_path' for nil:NilClass):
  
app/models/page_template.rb:49:in `template_dir'
app/models/page_template.rb:54:in `available_templates'
app/models/page_template.rb:64:in `<class:PageTemplate>'
app/models/page_template.rb:4:in `<main>'
app/controllers/pages_controller.rb:78:in `show_page'
app/controllers/pages_controller.rb:19:in `index'
```

_Originally posted by @maxvlc in https://github.com/denny/ShinyCMS-ruby/issues/287#issuecomment-619194806_

**Comment by denny** [comment]
Hey @maxvlc, I've moved this into a new issue to keep each problem separate :)

I've just been looking at this and I can't seem to provoke that error. It feels an empty string or a nil is slipping into the theme path somehow, but no matter what I set as theme name I'm not getting an error - just unthemed pages.

What do you have in your ENV and/or .env for ShinyCMS, and have you got the demo site data loaded or not?

**Comment by maxvlc** [comment]
Hi  @denny , finally all seems working fine.

Thanks for all!

![imagen](https://user-images.githubusercontent.com/3049189/80315451-ec56ba00-87f7-11ea-8dbc-880c649efaea.png)

**Comment by denny** [comment]
Great! Did you have to do anything that's not in the docs in the end? Let me know if they need anything adding, or if there's anything that could be made clearer / more helpful. :slightly_smiling_face:

**Comment by maxvlc** [comment]
Hi Denny,

Not at all, everything is in the docs.
Maybe just recommending to have a look at the `docs` folder is a plus to avoid loss of time re-reading the general `README.md`

Thankls!
